# Generated by Django 5.1.3 on 2024-11-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='inventory_capacity',
            field=models.CharField(max_length=20),
        ),
    ]
