# Generated by Django 5.1.3 on 2024-11-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='delivery_zones',
            field=models.TextField(max_length=255),
        ),
    ]
