# Generated by Django 5.1.3 on 2024-12-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartContract', '0003_rename_customer_approved_smartcontract_retailer_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartcontract',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='smartcontract',
            name='terms_and_conditions',
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='contract_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
