# Generated by Django 5.1.3 on 2024-11-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termsConditions', '0002_termsandconditions_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsandconditions',
            name='image',
        ),
    ]
