# Generated by Django 5.1.3 on 2024-11-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/products/'),
        ),
    ]
