# Generated by Django 5.1.3 on 2024-11-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='smart_contract',
        ),
    ]
