# Generated by Django 5.1.3 on 2024-11-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_transaction_smart_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='blockchain_hash',
            field=models.CharField(default=None, max_length=66, null=True),
        ),
    ]
