# Generated by Django 5.1.3 on 2024-11-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Kg')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Product Rate',
                'verbose_name_plural': 'Product Rates',
                'db_table': 'product_rate',
                'ordering': ['product_name'],
            },
        ),
    ]
